### ISSUE TITLE
Rework Java linking on OSX.

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-launcher#38]
The OSX profiles try to link against Java 6. However, as of El Capitan, the expected Headers directory is no longer present in Apple Java 6 installs.

Instead, we should update the profiles to check for the "include" directory that is used in java 7+.

**Comment by ctrueden** [comment]
I believe this issue is resolved. Certainly with efaea16049ded0adba625238bf9c769798c4a18a (authored before this issue was filed!), the launcher links to `libjli` instead of `libjvm` on macOS, and that avoids the popup purporting that legacy Java 6 is required to run the program. One related issue there was that `Info.plist` still referenced the old `ImageJ-tiger` launcher, which did not include that fix.

In any case, things seem to work well with OpenJDK 8 and Oracle JDK 8 now, when Java 6 is not installed on the system.
