### ISSUE TITLE
Don't rewrite icons when launching from within another application

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-launcher#44]
We received a report in the testing of ImageJ-MATLAB that launching from within MATLAB can replace the MATLAB icon with a Fiji icon.

I am hazy on the details but I thought the aggressive icon rewriting was a fix for OSX? I wasn't able to reproduce the issue personally on Ubuntu 14.04.

That said, if we can reproduce and isolate the issue, it would be great to be able to check if we're being called from another app or not, and avoid rewriting the icon in the former case.

**Comment by ctrueden** [comment]
This might be moot after we finally switch to JavaFX deployment...

**Comment by ctrueden** [comment]
We are switching the Fiji launcher to a new one we made called [Jaunch](https://github.com/apposed/jaunch). It does not have this problem, because it does not set the icon. It actually needs to set the icon in *some* cases (apposed/jaunch#31)—we should avoid reintroducing this bug when we implement that feature.
